spring:
  application:
    name: rudi-gateway
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=sec-login
        - RemoveRequestHeader=sec-type
        - RemoveRequestHeader=sec-firstname
        - RemoveRequestHeader=sec-lastname
        - RemoveRequestHeader=sec-email
        - RemoveRequestHeader=sec-organization
        - RemoveRequestHeader=sec-roles
      routes:
        - id: acl_service
          uri: lb://RUDI-ACL/
          predicates:
            - Path=/acl/**
        - id: acl_service_jwt
          uri: lb://RUDI-ACL/
          predicates:
            - Path=/authenticate
        - id: acl_service_jwt_refresh
          uri: lb://RUDI-ACL/
          predicates:
            - Path=/refresh_token
        - id: acl_service_oauth2
          uri: lb://RUDI-ACL/
          predicates:
            - Path=/oauth/**
        - id: kalim_service
          uri: lb://RUDI-KALIM/
          predicates:
            - Path=/kalim/**
        - id: konsult_service
          uri: lb://RUDI-KONSULT/
          predicates:
            - Path=/konsult/**
        - id: kos_service
          uri: lb://RUDI-KOS/
          predicates:
            - Path=/kos/**
        - id: projekt_service
          uri: lb://RUDI-projekt/
          predicates:
            - Path=/projekt/**
        - id: strukture_service
          uri: lb://RUDI-STRUKTURE/
          predicates:
            - Path=/strukture/**
        - id: konsent_service
          uri: lb://RUDI-KONSENT/
          predicates:
            - Path=/strukture/**
        - id: template_service
          uri: lb://RUDI-TEMPLATE/
          predicates:
            - Path=/template/**
